### ISSUE TITLE
license issues for functions that are borrowed from another package/library

### ISSUE THREAD

**Issue by mikeaalv** [artedison/Edison_Lab_Shared_Metabolomics_UGA#10]
Some functions are borrowed from other libraries. We need to check their license and whether we can reuse those functions. 

Functions in `/metabolomics_toolbox/packages/SECIM_GUI/loadFileFunctions/ and also duplicated` at `/metabolomics_toolbox/code/`. This is related to issue #8 

Please list other functions with license issues here.

Best.
Yue

**Comment by mikeaalv** [comment]
the function [peakfit](https://github.com/artedison/Edison_Lab_Shared_Metabolomics_UGA/blob/c526ecf466d1d111b1240947a88dcd3ab9a71f1e/metabolomics_toolbox/code/base_functions/peakfit.m) seems to be from another toolbox of T. C. O'Haver

**Comment by mikeaalv** [comment]
[slidefun](https://github.com/artedison/Edison_Lab_Shared_Metabolomics_UGA/blob/c526ecf466d1d111b1240947a88dcd3ab9a71f1e/metabolomics_toolbox/code/base_functions/slidefun.m)

**Comment by lauracmorris** [comment]
A few functions are code from other Mathworks File Exchange contributors. While there were references to publications or an author's name, the License file and Cite As information was not included in the comments of these few (7) functions. I added the Mathworks File Exchange License and included the current Cite As for the following files:

David Snyder
./metabolomics_toolbox/code/pipe2matlab.m
./metabolomics_toolbox/code/read_nmrp.m
./metabolomics_toolbox/code/LoadPipe.m
./metabolomics_toolbox/code/base_functions/get_header_data.m
./metabolomics_toolbox/code/base_functions/inc2ppm.m
./metabolomics_toolbox/packages/SECIM_GUI/loadFileFunctions/get_header_data.m
./metabolomics_toolbox/packages/SECIM_GUI/loadFileFunctions/inc2ppm.m
./metabolomics_toolbox/packages/SECIM_GUI/loadFileFunctions/pipe2matlab.m:
./metabolomics_toolbox/packages/SECIM_GUI/loadFileFunctions/read_nmrp.m


Tom O'Haver
./metabolomics_toolbox/code/base_functions/peakfit.m

Jos (10584)
./metabolomics_toolbox/code/base_functions/slidefun.m
