### ISSUE TITLE
dead tags in wiki

### ISSUE THREAD

**Issue by judgemt** [artedison/Edison_Lab_Shared_Metabolomics_UGA#11]
Some of the auto-generated wiki tags do not have working links, or no links at all. Category pages will need to be created, then these pages will need to be regenerated and pushed. So far, we've found the following dead links:

`CIVM-NMR
RidgeTracking`

**Comment by mikeaalv** [comment]
the problem on `RidgeTracking` has been fixed.

**Comment by judgemt** [comment]
Links were created for the CIVM-NMR and RidgeTracking pages
