### ISSUE TITLE
ridgetrace_power2_ext index exceeded

### ISSUE THREAD

**Issue by judgemt** [artedison/Edison_Lab_Shared_Metabolomics_UGA#13]
Index exceeds the number of array elements (6).

Error in ridgetrace_power2_ext (line 279)
  ridpoint(i,indopt(indtemp(1:maxaddon)))=1;

@mikeaalv the data I'm using are accessible in this workflow Dropbox (Edison_Lab@UGA)/Projects/clock/CIVM_paper_2/Acetate_QAX_project/NMRdata/processed/civm_ncrassa_qax_02/makeDirsTimeSeries_02.m

**Comment by judgemt** [comment]
@mikeaalv run from line 30

**Comment by mikeaalv** [comment]
Thank you for reporting this. I'm working on it.

**Comment by mikeaalv** [comment]
as the branch merged. this issue will be closed. Let me know if you have any more suggestions. thank you
