### ISSUE TITLE
NMRbox install

### ISSUE THREAD

**Issue by Gerardwx** [artedison/Edison_Lab_Shared_Metabolomics_UGA#18]
NMRbox at UConn Health has been asked to install the toolbox on NMRbox. Should we just use the current master, or would you prefer to create a named branch so we'll all know what version ended in NMRbox?

**Comment by judgemt** [comment]
@Gerardwx - just letting you know that we're discussing the best way to do this (including paths) and will get back to you soon. Thanks for your patience. 

Best,
Michael

**Comment by judgemt** [comment]
@Gerardwx, we've made a NMRbox_1.0 branch (link below) from our master branch. Thanks! 
https://github.com/artedison/Edison_Lab_Shared_Metabolomics_UGA/tree/NMRbox_1.0

**Comment by Gerardwx** [comment]
Thank you.
