### ISSUE TITLE
VisScores - distinguishableColors only works with Image Processing toolbox

### ISSUE THREAD

**Issue by judgemt** [artedison/Edison_Lab_Shared_Metabolomics_UGA#3]
This may or may not require modification, but is good to note. From the command window: 

Error in distinguishable_colors (line 93)
    C = makecform('srgb2lab');

Error in VisScores (line 56)
cmap=distinguishable_colors(max(Ycolor)+1); % currently, the actual integers have an effect on the colors
chosen

Error in workflow (line 292)
        VisScores(rs,PCA,[1,2],'Y',ones(size(rs,1),1),'conf_ellipse','true','showlegend',metadata.batch)

**Comment by mikeaalv** [comment]
Can you provide a minimal reproducible example as follows so that we can understand what's happening here? 

```
code
```

```
error message
```

**Comment by judgemt** [comment]
Install image processing toolbox from Matlab
